#!/bin/bash
#This script helps finding out prime numbers,and it's still under designing.
#2012-08-07,1st release by linus
homedir=/home/linus
i=2
count=0
read -p "Please input the end number:" end_num
while [ "$i" -le "$end_num" ]
do
   j=2
   x=0
   echo "scale=1;sqrt($i)*10" | bc | cut -d "." -f1  > $homedir/result
   t=$(cat $homedir/result)
   while [ "$(($j*10))" -le "$t" ]
   do
      eval m=$(($i%$j))
      if [ "$m" != "0" ];then
         j=$(($j+1))
      else
         x=1
         j=$i
      fi
   done
   if [ "$x" == "0" ];then
      count=$(($count+1))
      echo "Prime:No.$count:$i"
   fi
   i=$(($i+1))
done
rm -f $homedir/result
